version: "3.8"

services:
  db:
    image: postgres:13
    container_name: taiga-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
    volumes:
      - ./db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: taiga-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"

  # docker exec -it taiga-back python manage.py createsuperuser
  backend:
    image: taigaio/taiga-back
    container_name: taiga-back
    restart: unless-stopped
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: taiga
      POSTGRES_PASSWORD: taiga
      POSTGRES_HOST: db
      TAIGA_SECRET_KEY: "replace_this"
      TAIGA_SITES_SCHEME: "http"
      TAIGA_SITES_DOMAIN: "localhost:9000"
      EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
      CELERY_BROKER_URL: "amqp://guest:guest@rabbitmq:5672//"
      CELERY_RESULT_BACKEND: "rpc://"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

    volumes:
      - ./media:/taiga-back/media
      - ./static:/taiga-back/static

  frontend:
    image: taigaio/taiga-front
    container_name: taiga-front
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      TAIGA_URL: "http://localhost:8000"
    depends_on:
      - backend
